// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zkbfuxxbtfomrtnwnnxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprYmZ1eHhidGZvbXJ0bndubnhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODI4NjYsImV4cCI6MjA3MTQ1ODg2Nn0.L3gDT7SjKMOuMqOuUxKuLkXUHa7_5mraiDekan7PJaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);